get_platform_behavior_sessions was incorrectly filtering out 4x2
AllenInstitute/visual_behavior_analysis pull request #823
Opened 2022-07-03 22:09 UTC by matchings

because only ophys sessions have a project_code in the behavior_sessions table, the VisualBehaviorMultiscope4x2 behavior training sessions were not being properly filtered out in the get_platform_behavior_sessions_table() function. This PR adds a step to merge the project_codes from the ophys_experiment_table into the behavior_sessions table before filtering out the 4x2 sessions.

2022-07-06 20:57 UTC, matchings commented
@yavorska-iryna This issue is related to what is in the behavior sessions table, not ophys experiments table, so it shouldn't have any impact on clustering analysis of ophys data.

2022-07-11 17:54 UTC, alexpiet requested changes

2022-07-11 17:54 UTC, alexpiet commented on visual_behavior/data_access/utilities.py
> +    behavior_sessions['experience_level'] = 'None'
Should this either be `None` (as python type, not a string), or `"Training"`? Having a string with "None" is confusing

2022-07-11 17:54 UTC, alexpiet commented on visual_behavior/data_access/utilities.py
> +    behavior_sessions.at[indices, 'experience_level'] = 'Novel Training'
I think its very confusing to call this Novel Training.

2022-07-28 21:56 UTC, merged